# Site settings
title: 童建的博客
email: tstj9022@gmail.com
description: Jay Tong’s home 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jaytong.github.io" # the base hostname & protocol for your site
twitter_username: Tong_Jan
github_username:  jaytong90

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 童建
  email: tstj9022@gmail.com
  weibo: stressJ
  github: http://github.com/jaytong90
title: Jian's Blog                          #自定义常量

# avatar头像及Favicon
avatar: https://s1.ax1x.com/2022/08/24/vcvxzD.jpg
favicon: https://s1.ax1x.com/2022/08/24/vgFLo4.png

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

#disqus:
#  shortname: https-jaytongSPH-github-io
